### ISSUE TITLE
navbar contains data var object, what's the purpose?

### ISSUE THREAD

**Issue by paulvanbladel** [ducksoupdev/vue-webpack-typescript#10]
navbar.ts contains:
 object: { default: string } = { default: 'Default object property!' }; // objects as default values don't need to be wrapped into functions

What's the idea here?
thanks

**Comment by ducksoupdev** [comment]
This is a comment to show the difference with declaring data properties from standard Vue where data must be declared as a function that returns the initial data object. See https://vuejs.org/v2/api/#data

**Comment by paulvanbladel** [comment]
thanks. Learned something.
