### ISSUE TITLE
Support for Font Awesome

### ISSUE THREAD

**Issue by ocanbascil** [ducksoupdev/vue-webpack-typescript#13]
I was trying to add support for Font Awesome, however I cannot get the font files to be referred correctly:

I have the following updates:

` "copy:fa": "ncp node_modules/font-awesome/css/font-awesome.css src/css/font-awesome.css && ncp node_modules/font-awesome/fonts/ src/fonts/"`

`"build": "cross-env NODE_ENV=production npm run clean && npm run test && npm run sass && npm run copy:bs && npm run copy:fa && npm run build:parts && npm run clean:css && npm run process:html"`

However the disted CSS still refers to the fonts from within `/src` directory. I am pretty sure we need to update the webpack config somehow, but definitely not an expert on it so I'm stuck at this step.

Would love to hear your thoughts.

Thanks

**Comment by ducksoupdev** [comment]
Hi, apologies for the delay in replying. I would recommend using sass for loading the font-awesome styles. 

Here is a sample from one of my projects. 

1. Create a main sass file for your project and import the font-awesome sass stylesheet.

```scss
// font-awesome
@import "~font-awesome/scss/font-awesome.scss"; // the ~ prefix tells webpack to load from the node_modules directory

// other project styles
body {...}
```
2. Add `sass-loader`, `css-loader` and `style-loader` as node dependencies.

3. Update the webpack base config file at `config/webpack.config.base.js` and add a rule for loading the sass and font files:

```javascript
...
module: {
  rules: [
    ...
    {
      test: /\.scss$/,
      use: [
        { loader: "style-loader" },
        { loader: "css-loader" },
        { loader: "sass-loader" }
      ]
    },
    {
      test: /\.(eot|svg|ttf|woff|woff2)$/,
      loader: "file-loader"
    }
  ],
},
...
```

4. Update your `src/main.ts` file and import the the main sass file near the top of the file:

```typescript
...
import "./sass/main.scss";
...
```

This will load, compile and inject your styles into your app.

Hope this helps?

**Comment by ducksoupdev** [comment]
The latest release https://github.com/ducksoupdev/vue-webpack-typescript/tree/v0.9.0 now has built-in support for sass loading. Bootstrap sass is now loaded through webpack so it should make it easier to integrate font-awesome. Let me know if it works?
