### ISSUE TITLE
Sass hot reload don't seem to be working

### ISSUE THREAD

**Issue by raizam** [ducksoupdev/vue-webpack-typescript#19]
Hi,

Editing main.scss while running the dev server doesn't reload the css, and having this message in the console:

```
=> changed: D:\dev\my-project\src\sass\main.scss
{
  "status": 3,
  "message": "%",
  "formatted": "Internal Error: %\n"
} 

```

I tried with a fresh template installed via vue-cli. My npm has nothing installed globally except vue-cli.
Can anyone try and confirm the behavior?

**Comment by ducksoupdev** [comment]
Hi, apologies for the delay in replying. The latest release https://github.com/ducksoupdev/vue-webpack-typescript/tree/v0.9.0 now integrates sass loading into webpack so editing the sass should reload the styles in development. Can you give it a try and let me know how you get on?
