### ISSUE TITLE
Single file components

### ISSUE THREAD

**Issue by vahdet** [ducksoupdev/vue-webpack-typescript#32]
I appreciate the work done 👏
However, I was a bit curious if you did not use [Single File Component approach](https://vuejs.org/v2/guide/single-file-components.html) deliberately.

**Comment by ducksoupdev** [comment]
Thank you. The template was created out of a requirement to separate TS files from markup, css etc.  This is purely a personal (and team) preference. This separation helps when using editors. SFC requires specific tooling. The great thing about Vue is that it is a progressive framework and therefore can support multiple project styles and patterns in addition to playing well with tools like Webpack.
