### ISSUE TITLE
How about creating few services like LoginService

### ISSUE THREAD

**Issue by arihantdaga** [ducksoupdev/vue-webpack-typescript#37]
Any idea about how we can write a stateful loginService which can be used across all components in typescript ? Without creating different instance of it in every component.

**Comment by ducksoupdev** [comment]
The simplest approach is to create a singleton class for that. Alternatively, you could use Vuex for managing login state.

**Comment by ducksoupdev** [comment]
An example singleton class would look like this:

```ts
class LoginService {

  private static _instance: LoginService;

  private constructor() {
  }

  static createInstance() {
    LoginService.getInstance();
  }

  static getInstance() {
    return this._instance || (this._instance = new this());
  }

}
```

**Comment by ducksoupdev** [comment]
If you are interested in Vuex, I would recommend using [`vuex-typescript`](https://www.npmjs.com/package/vuex-typescript) as it is a simple way to get static typing, static code analysis and intellisense with the Vuex library.
