### ISSUE TITLE
Any idea why Vue is imported as "import * as Vue from 'vue'' ?

### ISSUE THREAD

**Issue by paulvanbladel** [ducksoupdev/vue-webpack-typescript#7]
Very nice project and clever test approach.

I'm just wondering why we have e.g. in main.ts
import * as Vue from 'vue';
rather than import Vue from 'vue' as it 

Warm regards
paul.

**Comment by ducksoupdev** [comment]
Thanks :)

There are a few things that need changing, this is one of them. I am planning to uplift to the latest version so will change this as well.

**Comment by paulvanbladel** [comment]
Looking forward to that !
So nice you got rid of the .vue files :)

Don't want to bother you with too many questions (so feel free to just disregard this question) , but I'm wondering what's the way to go to test the viewModel on the level of the viewmodel data rather than the underlying html.
E.g. simple example : your about.ts has a REPO data property. How can i test if this is correctly set

 expect(vm.$data, ...... )
I don't see a way how I can consule the $data prop?

Thanks
paul.

**Comment by ducksoupdev** [comment]
I normally test the components from what the output is. For example, If I am expecting a REPO property to be displayed on a particular component for an element with class `.repo-link` then I assert that the property value is bound correctly to that element.

**Comment by ducksoupdev** [comment]
I have updated the template to Vue 2.2 including using es2015 style imports. https://github.com/ducksoupdev/vue-webpack-typescript/tree/v0.4.0

**Comment by paulvanbladel** [comment]
Regarding the above problem I had accessing the props and methods when component is created the way you do in the tests, I posted following on stackoverflow:
http://stackoverflow.com/questions/42876203/different-behavior-when-component-is-created-via-vue-extend-or-via-new-vue

I think there can be occasions to have access to the full viewModel.
If i get the correct answer, I'll prepare a PR for an additional test in your sample illustrating the technique.
Cheers.
