### ISSUE TITLE
Debugging tests doesn't seem to work.

### ISSUE THREAD

**Issue by paulvanbladel** [ducksoupdev/vue-webpack-typescript#8]
With the webpack template (in vue-cli), I can add following npm script and allow debugging tests. This doesn't work with vue-webpack-typescript template.

"debug- unit": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --browsers=Chrome --single-run=false --auto-watch",

I tweaked the karma.unit.js file in order to use also Chrome browser, but still no success:
 browsers:['Chrome'],
  preprocessors: {
      'src/test.ts': ['webpack','sourcemap']
    },

Obviously, following packages need to be installed
  "karma-chrome-launcher": "^2.0.0",
    "karma-sourcemap-loader": "^0.3.7",
Any suggestion?

**Comment by ducksoupdev** [comment]
I will investigate the debugging and let you know

**Comment by ducksoupdev** [comment]
I have created an upgrade project that I use for upgrading the template - https://github.com/ducksoupdev/vue-webpack-ts-upgrade

This includes uplifting for Vue 2.2 and includes better tests, teamcity and jenkins integration as well as updated karma config for watching and coverage.

I have included a karma debug config which attempts to allow debugging of webpack via sourcemaps. It isn't quite right though and needs looking at but it's an effort to provide this sort of functionality. If you have time, it would be great to get your feedback on it?

**Comment by paulvanbladel** [comment]
Brilliant.
AT first glance I didn't understand why you did not create a separate branch for this, but now I understand, the vue-webpack-ts-upgrade project is like a project created with the eventual template whereas vue-webpack-ts is the template itself :)
If will definitely look today in great detail into it and provide feedback.

**Comment by paulvanbladel** [comment]
Very nice,
Already some first feedback:

- the types for axios are missing. Specific reason?
- I  tried to run a test with npm run test-debug but I couldn't hit a breakpoint (set upfront in code explicitely with a debugger statement (so I do not depend on an editor for debugging). So, after npm run test-debug I click the debug button in the karma browser window, open dev tools, but no breakpoint is hit. I'll investigate and if I find a solution, I'll make a PR.
- just for my understanding: the way you git rid of import * as Vue from vue, was this solely achieved by the updated tsconfig.son?

I really believe in this project, the point is that for serious enterprise app dev, both typescript and excellent support for unit testing are indispensable. I'll think about how you could "position" the template in a more attractive way...

**Comment by ducksoupdev** [comment]
Thanks for taking a look. 

The types for axios are included with the npm package so no need for the separate `@types/axios`. The removal of `import * as Vue from 'vue'` was down to the tsconfig change. This helped with the upgrade to Vue 2.2 as detailed here https://vuejs.org/v2/guide/typescript.html#Important-2-2-Change-Notice-for-TS-webpack-2-users.

Thanks for the PR too :) I did look at the `webpack.SourceMapDevToolPlugin` plugin but didn't get to trying it out. Will have a play with your changes and come back to you.

**Comment by ducksoupdev** [comment]
Test debugging using Chrome is now available in v0.6.0
