### ISSUE TITLE
DEV/PRO aware build setup

### ISSUE THREAD

**Issue by paulvanbladel** [ducksoupdev/vue-webpack-typescript#9]
I'm using a proxy table in the regular webpack template (https://github.com/vuejs-templates/webpack/tree/master/template).  I can configure that it is only applied in "dev mode".
This is not (yet) possible in vue-webpack-typescript.  

I believe that, in general, it should be beneficial to take over as much as possible from the regular vue webpack template. The advantage is two fold: 
1. it will be easier to take over 'progressive insights' when the standard vue template evolves.
2. it will increase the adoption rate of vue-webpack-typescript because devs will easier see where the differences are and adopt with greater confidence.
Make sense ?

**Comment by ducksoupdev** [comment]
This makes sense. I initially created this from the simple webpack template with the plan to add more as it grew. I guess this would be useful now! Happy to make you an admin on the repo if you are happy to work on adding that feature?

**Comment by paulvanbladel** [comment]
That's very kind but to be honest I have not that much insights in the internals of the whole build process. I'll try to prepare something on my fork of vue-webpack-ts-upgrade.  I'll keep you posted. 
cheers.

**Comment by ducksoupdev** [comment]
Just out of interest, do you proxy to a running API or a mocked one?

**Comment by paulvanbladel** [comment]
to a running api. For prototyping I use express (nodejs), but for production I use .Net.

**Comment by paulvanbladel** [comment]
may I ask something about your latest sample where you new up in several places a Log class.
I have the feeling (not with your log class but with similar things I'm doing), that there can be "race conditions" when constructing the same class in several places.
Rings a bell?

**Comment by ducksoupdev** [comment]
I have not encountered race conditions like this although I tend to create a singleton logger and use it everywhere within the app so the logging output is through one configured class. I use a pattern like this:

``` javascript
class LoggingService {
  private static _instance: LoggingService;

  private constructor() {
  }

  static createInstance() {
    LoggingService.getInstance();
  }

  static getInstance() {
    return this._instance || (this._instance = new this());
  }
}

const logger = LoggingService.getInstance();
```

**Comment by paulvanbladel** [comment]
yeah, that's what I had in mind as well.
